<a href="https://colab.research.google.com/github/bhanu-4290/Ai-and-ML/blob/main/Thremal_data_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("/content/Folds5x2_pp.csv")
df

AT      V       AP     RH      PE
0      8.34  40.77  1010.84  90.01  480.48
1     23.64  58.49  1011.40  74.20  445.75
2     29.74  56.90  1007.15  41.91  438.76
3     19.07  49.69  1007.22  76.79  453.09
4     11.80  40.66  1017.13  97.20  464.43
...     ...    ...      ...    ...     ...
9563  15.12  48.92  1011.80  72.93  462.59
9564  33.41  77.95  1010.30  59.72  432.90
9565  15.99  43.34  1014.20  78.66  465.96
9566  17.65  59.87  1018.58  94.65  450.93
9567  23.68  51.30  1011.86  71.24  451.67

[9568 rows x 5 columns]

In [ ]:
#data exploration
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9568 entries, 0 to 9567
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   AT      9568 non-null   float64
 1   V       9568 non-null   float64
 2   AP      9568 non-null   float64
 3   RH      9568 non-null   float64
 4   PE      9568 non-null   float64
dtypes: float64(5)
memory usage: 373.9 KB


In [ ]:
df.columns

Index(['AT', 'V', 'AP', 'RH', 'PE'], dtype='object')

In [ ]:
df.shape

(9568, 5)

In [ ]:
df.rename(columns={"AT":"Average_Temperature",
                   'V':"Exhuast_Vacuume",
                   "AP":"Ambient_Pressure",
                   'RH':"Relative_Humidity",
                   'PE':"Net_Hourly_Electrical_Energy_Consumption"},inplace=True)

In [ ]:
df

Average_Temperature  Exhuast_Vacuume  Ambient_Pressure  \
0                    8.34            40.77           1010.84   
1                   23.64            58.49           1011.40   
2                   29.74            56.90           1007.15   
3                   19.07            49.69           1007.22   
4                   11.80            40.66           1017.13   
...                   ...              ...               ...   
9563                15.12            48.92           1011.80   
9564                33.41            77.95           1010.30   
9565                15.99            43.34           1014.20   
9566                17.65            59.87           1018.58   
9567                23.68            51.30           1011.86   

      Relative_Humidity  Net_Hourly_Electrical_Energy_Consumption  
0                 90.01                                    480.48  
1                 74.20                                    445.75  
2                 41.91                                    438.76  
3                 76.79                                    453.09  
4                 97.20                                    464.43  
...                 ...                                       ...  
9563              72.93                                    462.59  
9564              59.72                                    432.90  
9565              78.66                                    465.96  
9566              94.65                                    450.93  
9567              71.24                                    451.67  

[9568 rows x 5 columns]

In [ ]:
df.corr()

Average_Temperature  \
Average_Temperature                                  1.000000   
Exhuast_Vacuume                                      0.844107   
Ambient_Pressure                                    -0.507549   
Relative_Humidity                                   -0.542535   
Net_Hourly_Electrical_Energy_Consumption            -0.948128   

                                          Exhuast_Vacuume  Ambient_Pressure  \
Average_Temperature                              0.844107         -0.507549   
Exhuast_Vacuume                                  1.000000         -0.413502   
Ambient_Pressure                                -0.413502          1.000000   
Relative_Humidity                               -0.312187          0.099574   
Net_Hourly_Electrical_Energy_Consumption        -0.869780          0.518429   

                                          Relative_Humidity  \
Average_Temperature                               -0.542535   
Exhuast_Vacuume                                   -0.312187   
Ambient_Pressure                                   0.099574   
Relative_Humidity                                  1.000000   
Net_Hourly_Electrical_Energy_Consumption           0.389794   

                                          Net_Hourly_Electrical_Energy_Consumption  
Average_Temperature                                                      -0.948128  
Exhuast_Vacuume                                                          -0.869780  
Ambient_Pressure                                                          0.518429  
Relative_Humidity                                                         0.389794  
Net_Hourly_Electrical_Energy_Consumption                                  1.000000

In [ ]:
# SPlit the data bet Independant Features and dependant features
X = df.drop('Net_Hourly_Electrical_Energy_Consumption',axis=1).values
X

array([[   8.34,   40.77, 1010.84,   90.01],
       [  23.64,   58.49, 1011.4 ,   74.2 ],
       [  29.74,   56.9 , 1007.15,   41.91],
       ...,
       [  15.99,   43.34, 1014.2 ,   78.66],
       [  17.65,   59.87, 1018.58,   94.65],
       [  23.68,   51.3 , 1011.86,   71.24]])

In [ ]:
y= df['Net_Hourly_Electrical_Energy_Consumption'].values
y


array([480.48, 445.75, 438.76, ..., 465.96, 450.93, 451.67])

In [ ]:
# split the data into train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.80,random_state=1)
X_train

array([[  20.14,   46.93, 1014.66,   64.22],
       [  25.52,   63.94, 1017.81,   41.54],
       [  15.01,   39.52, 1017.53,   72.  ],
       ...,
       [  10.22,   39.64, 1010.72,   63.05],
       [  20.32,   44.6 , 1015.16,   36.35],
       [  17.37,   41.23,  998.79,   68.44]])

In [ ]:
y_train

array([453.99, 440.32, 468.02, ..., 477.22, 460.21, 461.08])

In [ ]:
# feature scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler

StandardScaler()

In [ ]:
X_train_scaled = scaler.fit_transform(X_train)
X_train_scaled

array([[ 0.04970432, -0.58563616,  0.22630094, -0.55350512],
       [ 0.7576002 ,  0.74180947,  0.76758053, -2.09383509],
       [-0.62529677, -1.16390613,  0.71946679, -0.02512032],
       ...,
       [-1.25556095, -1.15454143, -0.45072814, -0.63296658],
       [ 0.07338857, -0.76746734,  0.31221834, -2.44631801],
       [-0.31476995, -1.03045921, -2.50071719, -0.26690051]])

In [ ]:
X_test_scaled = scaler.transform(X_test)
X_test_scaled


array([[-0.25819091, -0.83614177, -0.79611607,  0.41633227],
       [ 1.29444317,  1.30369122, -0.32357039, -1.3365741 ],
       [-1.14503445, -1.38319609,  1.43086283,  0.54808889],
       ...,
       [ 0.87075828, -0.74483599, -0.72222711, -1.39769831],
       [-1.65293001, -1.09913365, -0.25999152,  1.57701302],
       [ 1.24049572,  1.02040917, -0.3201337 , -1.14233496]])

In [ ]:
#model architecture
df.shape

(9568, 5)

In [ ]:
import tensorflow as tf
from  tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
#hidden layers
model = Sequential()
model.add(tf.keras.layers.Input(shape=[4], name="Input_Layer"))
model.add(Dense(units=16, activation='relu', name= "Hidden_Layer_1"))
model.add(Dense(units=8, activation='elu', name = "Hidden_layer_2"))
model.add(Dense(units=1, name = "output_layer"))

In [ ]:
model.compile(
    loss = "mean_squared_error",
    optimizer = "adam"
)

In [ ]:
from tensorflow.keras.callbacks import EarlyStopping


In [ ]:
 model.fit(
    x = X_train_scaled,
    y = y_train,
    epochs = 100,
    batch_size = 32,
    validation_data = (X_test_scaled,y_test),
    callbacks = EarlyStopping(monitor="val_loss",patience=10)
)


Epoch 1/100
60/60 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 206732.1719 - val_loss: 205391.2031
Epoch 2/100
60/60 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 204615.5625 - val_loss: 203725.9844
Epoch 3/100
60/60 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 203437.2031 - val_loss: 200840.0469
Epoch 4/100
60/60 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 200348.4688 - val_loss: 196219.7031
Epoch 5/100
60/60 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 195069.0938 - val_loss: 189099.2500
Epoch 6/100
60/60 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 186721.5781 - val_loss: 178652.9688
Epoch 7/100
60/60 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 174712.8438 - val_loss: 164173.9531
Epoch 8/100
60/60 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 159375.4219 - val_loss: 145873.0469
Epoch 9/100
60/60 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 139472.0781 - val_loss: 124778.5625
Epoch 10/100
60/60 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 118001.8672 - val_loss: 102393.1719
Epoch 11/100
60/60 ━━━━━━━━━━━━━━━━━━━━ 

In [ ]:
model.history.history

{'loss': [206072.5,
  204742.4375,
  202501.21875,
  198793.203125,
  192980.28125,
  184228.6875,
  171708.828125,
  155141.984375,
  135141.109375,
  113059.65625,
  90693.0703125,
  70020.0625,
  52675.8046875,
  39543.23046875,
  30616.958984375,
  24974.765625,
  21554.146484375,
  19354.955078125,
  17757.814453125,
  16431.41796875,
  15226.423828125,
  14098.0673828125,
  12998.1982421875,
  11939.009765625,
  10906.357421875,
  9906.87890625,
  8954.8359375,
  8046.142578125,
  7184.3037109375,
  6383.03955078125,
  5637.53759765625,
  4950.73583984375,
  4321.1435546875,
  3751.643310546875,
  3244.505126953125,
  2799.980712890625,
  2411.683837890625,
  2073.058837890625,
  1780.762451171875,
  1535.6458740234375,
  1331.524169921875,
  1159.2110595703125,
  1016.9147338867188,
  900.4857177734375,
  802.60888671875,
  720.8501586914062,
  651.5657348632812,
  593.5303955078125,
  542.8360595703125,
  499.18438720703125,
  459.9619140625,
  425.85296630859375,
  394.2314147

In [ ]:
pd.DataFrame(model.history.history)

loss       val_loss
0   206072.500000  205391.203125
1   204742.437500  203725.984375
2   202501.218750  200840.046875
3   198793.203125  196219.703125
4   192980.281250  189099.250000
..            ...            ...
95      48.785675      48.122238
96      47.420425      47.379314
97      46.338760      46.178806
98      45.003506      43.968586
99      43.841900      43.132984

[100 rows x 2 columns]

In [ ]:
model.evaluate(X_train_scaled, y_train)

60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 42.8293


43.01627731323242

In [ ]:

model.evaluate(X_test_scaled, y_test)

240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 42.8650


43.13298416137695

In [ ]:
prediction = model.predict(X_test_scaled)
prediction

240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step


array([[457.0017 ],
       [437.14142],
       [475.70355],
       ...,
       [445.48523],
       [484.46576],
       [438.07123]], dtype=float32)

In [ ]:
prediction_df = pd.DataFrame(np.ravel(prediction),columns = ['predictions'])
prediction_df

predictions
0      457.001709
1      437.141418
2      475.703552
3      439.505615
4      449.376709
...           ...
7650   452.383667
7651   465.592865
7652   445.485229
7653   484.465759
7654   438.071228

[7655 rows x 1 columns]

In [ ]:
compare_df = pd.concat([pd.DataFrame(y_test,columns=['true_values']),prediction_df],axis=1)
compare_df

true_values  predictions
0          458.92   457.001709
1          430.55   437.141418
2          473.85   475.703552
3          435.02   439.505615
4          456.44   449.376709
...           ...          ...
7650       457.07   452.383667
7651       466.85   465.592865
7652       442.13   445.485229
7653       484.90   484.465759
7654       446.97   438.071228

[7655 rows x 2 columns]